(function () {
  const KEY = 'constructionDemoDataV1';
  const DAY = 86400000;
  const roles = {GIAM_DOC:'Giám đốc',CHT:'Chỉ huy trưởng',KY_THUAT:'Kỹ thuật / Giám sát',KE_TOAN:'Kế toán'};
  const permissions = {view:['GIAM_DOC','CHT','KY_THUAT','KE_TOAN'],'money.view':['GIAM_DOC','CHT','KE_TOAN'],'report.create':['CHT','KY_THUAT'],'report.review':['GIAM_DOC','CHT'],'cost.create':['KE_TOAN'],'budget.import':['GIAM_DOC','KE_TOAN'],'catalog.manage':['GIAM_DOC','CHT'],'demo.reset':['GIAM_DOC']};
  const pad = n => String(n).padStart(2,'0');
  const date = d => `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
  const add = (value,days) => {const d=new Date((typeof value==='string'?value:date(value))+'T12:00:00');d.setDate(d.getDate()+days);return date(d)};
  const today = () => date(new Date());
  const days = (a,b) => Math.round((new Date(b+'T12:00:00')-new Date(a+'T12:00:00'))/DAY);
  const clone = value => JSON.parse(JSON.stringify(value));
  const moneyFields = new Set(['giaTriHopDong','duToan','thucChi','conLai','ptChi','trangThaiChiPhi','chiVuotTienDo','canhBaoChiPhi','costBreakdown','budgetRows','costRows','costChart','dgVatLieu','dgNhanCong','dgMay','thanhTien','soTien']);
  const stripMoney = value => Array.isArray(value)?value.map(stripMoney):value&&typeof value==='object'?Object.fromEntries(Object.entries(value).filter(([k])=>!moneyFields.has(k)).map(([k,v])=>[k,stripMoney(v)])):value;
  function requirePerm(ctx,perm){if(!(permissions[perm]||[]).includes(ctx&&ctx.role))throw new Error('Bạn không có quyền thực hiện thao tác này.')}
  function nextId(rows,prefix,digits){const max=rows.reduce((m,r)=>Math.max(m,Number(String(r.id||'').replace(prefix,''))||0),0);return prefix+String(max+1).padStart(digits,'0')}
  function plan(item,at=today()){if(at<item.ngayBatDau)return 0;if(at>=item.ngayKetThuc)return 100;return Math.max(0,Math.min(100,(days(item.ngayBatDau,at)+1)/(days(item.ngayBatDau,item.ngayKetThuc)+1)*100))}
  function progressStatus(actual,planned,end){if(actual>=100)return{code:'HOAN_THANH',label:'Hoàn thành',color:'green'};if(today()>end)return{code:'QUA_HAN',label:'Quá hạn',color:'red'};const diff=planned-actual;return diff>=10?{code:'CHAM',label:'Chậm',color:'red'}:diff>=5?{code:'CAN_CHU_Y',label:'Cần chú ý',color:'yellow'}:{code:'DUNG_TIEN_DO',label:'Đúng tiến độ',color:'green'}}
  function costStatus(percent,has){if(!has)return{code:'CHUA_CO_DU_TOAN',label:'Chưa có dự toán',color:'muted'};return percent>=100?{code:'VUOT_DU_TOAN',label:'Vượt dự toán',color:'red'}:percent>=80?{code:'SAP_VUOT',label:'Sắp vượt',color:'yellow'}:{code:'TRONG_NGAN_SACH',label:'Trong ngân sách',color:'green'}}
  function seed(){const now=today(),defs=[['CT-0001','Nhà xưởng KCN Yên Phong – Bắc Ninh','KCN Yên Phong, Bắc Ninh',-90,60,18500000000,'Trần Minh Đức',1,.58],['CT-0002','Trường mầm non Hoa Sen – Hà Đông','Hà Đông, Hà Nội',-60,90,9200000000,'Đỗ Văn Hùng',.55,.25],['CT-0003','Nhà phố 5 tầng – Cầu Giấy','Cầu Giấy, Hà Nội',-45,75,4800000000,'Phạm Quốc Bảo',1,1.03]];
    const projects=defs.map((x,i)=>({id:x[0],ten:x[1],chuDauTu:'Chủ đầu tư Demo',diaDiem:x[2],ngayKhoiCong:add(now,x[3]),ngayHoanThanh:add(now,x[4]),giaTriHopDong:x[5],chiHuyTruong:x[6],trangThai:'DANG_THI_CONG',createdAt:add(now,x[3]-5)}));
    const names=[['Chuẩn bị mặt bằng','m2',4000,0,.13,.05],['Ép cọc BTCT 300x300','md',900,.08,.3,.12],['Đào đất móng','m3',1800,.19,.39,.1],['Bê tông móng','m3',700,.3,.53,.15],['Kết cấu thân / khung thép','tấn',500,.43,.8,.32],['Xây tường và hoàn thiện','m2',3200,.63,1,.26]],factors=[1,.62,.28],workItems=[],budgets=[],reports=[],costs=[];
    projects.forEach((p,pi)=>{const duration=days(p.ngayKhoiCong,p.ngayHoanThanh),items=[];names.forEach((n,ii)=>{const h={id:'HM-'+String(pi*6+ii+1).padStart(4,'0'),congTrinhId:p.id,stt:ii+1,ten:n[0],donVi:n[1],klKeHoach:n[2]*factors[pi],ngayBatDau:add(p.ngayKhoiCong,Math.round(duration*n[3])),ngayKetThuc:add(p.ngayKhoiCong,Math.round(duration*n[4]))};items.push(h);workItems.push(h);['Vật liệu','Nhân công','Máy'].forEach((label,k)=>{const ratios=[.65,.25,.1],target=p.giaTriHopDong*.88*n[5]*ratios[k],unit=Math.round(target/h.klKeHoach);budgets.push({id:'DT-'+String(budgets.length+1).padStart(5,'0'),congTrinhId:p.id,hangMucId:h.id,maHieu:['AF.11213','AB.25112','AF.61130'][k],noiDung:label+' – '+h.ten,donVi:h.donVi,khoiLuong:h.klKeHoach,dgVatLieu:k===0?unit:0,dgNhanCong:k===1?unit:0,dgMay:k===2?unit:0,thanhTien:Math.round(unit*h.klKeHoach)})});const actual=Math.min(100,plan(h)*defs[pi][7]);if(actual>0)reports.push({id:'BC-'+String(reports.length+1).padStart(6,'0'),ngay:add(now,-3-ii),congTrinhId:p.id,hangMucId:h.id,klThucHien:h.klKeHoach*actual/100,soNhanCong:12+ii,mayMoc:'1 máy xúc, 1 cẩu',thoiTiet:pi===1?'MUA':'NANG',vuongMac:pi===1&&ii===2?'Chậm cấp vật tư':'',anh:'',photoUrls:[],nguoiBaoCao:pi===0?'Lê Hoàng Nam':'Kỹ thuật công trường',trangThai:'DA_DUYET',nguoiDuyet:p.chiHuyTruong,ghiChuDuyet:'',ngayDuyet:add(now,-2)+' 18:00:00',createdAt:add(now,-3-ii)+' 17:00:00'})});
      for(let i=0;i<7;i++){const h=items[i%Math.max(1,items.length-2)];reports.push({id:'BC-'+String(reports.length+1).padStart(6,'0'),ngay:add(now,-(i%3)),congTrinhId:p.id,hangMucId:h.id,klThucHien:h.klKeHoach*.01,soNhanCong:15+i,mayMoc:'1 máy trộn',thoiTiet:'AM_U',vuongMac:'',anh:'',photoUrls:[],nguoiBaoCao:pi===0?'Lê Hoàng Nam':'Kỹ thuật công trường',trangThai:i===6?'TRA_LAI':'CHO_DUYET',nguoiDuyet:'',ghiChuDuyet:i===6?'Cần bổ sung mô tả khối lượng.':'',ngayDuyet:'',createdAt:add(now,-(i%3))+' 17:30:00'})}
      const totalBudget=budgets.filter(b=>b.congTrinhId===p.id).reduce((s,b)=>s+b.thanhTien,0),target=totalBudget*defs[pi][8],types=[['VAT_LIEU',.55],['NHAN_CONG',.25],['MAY',.15],['KHAC',.05]];types.forEach((t,i)=>costs.push({id:'CP-'+String(costs.length+1).padStart(6,'0'),ngay:add(now,-7*(i+1)),congTrinhId:p.id,hangMucId:items[i].id,loai:t[0],noiDung:'Chi phí '+t[0].toLowerCase(),soTien:Math.round(target*t[1]),nhaCungCap:'Nhà cung cấp Demo',soChungTu:'CT-'+p.id.slice(-4)+'-'+(i+1),nguoiNhap:'Phạm Thu Hà',createdAt:add(now,-7*(i+1))+' 16:00:00'}))});
    const data={projects,workItems,budgets,reports,costs};localStorage.setItem(KEY,JSON.stringify(data));return data}
  function load(){try{return JSON.parse(localStorage.getItem(KEY))||seed()}catch(e){return seed()}}
  function save(data){localStorage.setItem(KEY,JSON.stringify(data))}
  function compute(data,at=today()){const summaries=data.projects.map(p=>{const items=data.workItems.filter(h=>h.congTrinhId===p.id).map(h=>{const approved=data.reports.filter(r=>r.hangMucId===h.id&&r.trangThai==='DA_DUYET'&&r.ngay<=at),done=approved.reduce((s,r)=>s+Number(r.klThucHien),0),actual=Math.min(100,done/Number(h.klKeHoach)*100||0),planned=plan(h,at),budget=data.budgets.filter(b=>b.hangMucId===h.id).reduce((s,b)=>s+Number(b.thanhTien),0),spent=data.costs.filter(c=>c.hangMucId===h.id).reduce((s,c)=>s+Number(c.soTien),0),pct=budget?spent/budget*100:null;return{...h,klLuyKe:+done.toFixed(2),ptThucTe:+actual.toFixed(2),ptKeHoach:+planned.toFixed(2),trangThaiTienDo:progressStatus(actual,planned,h.ngayKetThuc),duToan:budget,thucChi:spent,conLai:budget-spent,ptChi:pct===null?null:+pct.toFixed(2),trangThaiChiPhi:costStatus(pct||0,!!budget),chiVuotTienDo:pct===null?null:+(pct-actual).toFixed(2),canhBaoChiPhi:pct!==null&&pct-actual>10?'Chi tiêu nhanh hơn tiến độ thi công':''}}),has=items.some(h=>h.duToan),weight=h=>has?h.duToan:1,total=items.reduce((s,h)=>s+weight(h),0),actual=total?items.reduce((s,h)=>s+h.ptThucTe*weight(h),0)/total:0,planned=total?items.reduce((s,h)=>s+h.ptKeHoach*weight(h),0)/total:0,budget=items.reduce((s,h)=>s+h.duToan,0),spent=items.reduce((s,h)=>s+h.thucChi,0),pct=budget?spent/budget*100:null;return{...p,ptThucTe:+actual.toFixed(2),ptKeHoach:+planned.toFixed(2),lechTienDo:+(planned-actual).toFixed(2),trangThaiTienDo:progressStatus(actual,planned,p.ngayHoanThanh),duToan:budget,thucChi:spent,conLai:budget-spent,ptChi:pct===null?null:+pct.toFixed(2),trangThaiChiPhi:costStatus(pct||0,!!budget),chiVuotTienDo:pct===null?null:+(pct-actual).toFixed(2),canhBaoChiPhi:pct!==null&&pct-actual>10?'Chi tiêu nhanh hơn tiến độ thi công':'',hangMuc:items}});return summaries}
  function enrichReports(data,rows){return rows.map(r=>({...r,congTrinhTen:data.projects.find(p=>p.id===r.congTrinhId)?.ten||'',hangMucTen:data.workItems.find(h=>h.id===r.hangMucId)?.ten||'',donVi:data.workItems.find(h=>h.id===r.hangMucId)?.donVi||'',photoUrls:r.photoUrls||[]}))}
  const api={
    api_getBootstrap(ctx){requirePerm(ctx,'view');const d=load(),s=compute(d),result={companyName:'Công ty CP Xây dựng Demo',projects:s.map(p=>({id:p.id,ten:p.ten,trangThai:p.trangThai,ptThucTe:p.ptThucTe,ptKeHoach:p.ptKeHoach,duToan:p.duToan,thucChi:p.thucChi,ptChi:p.ptChi,trangThaiTienDo:p.trangThaiTienDo,trangThaiChiPhi:p.trangThaiChiPhi})),workItems:s.flatMap(p=>p.hangMuc.map(h=>({id:h.id,congTrinhId:h.congTrinhId,stt:h.stt,ten:h.ten,donVi:h.donVi,klKeHoach:h.klKeHoach,klLuyKe:h.klLuyKe,ngayBatDau:h.ngayBatDau,ngayKetThuc:h.ngayKetThuc}))),roles,enums:{}};return ctx.role==='KY_THUAT'?stripMoney(result):result},
    api_getDashboard(ctx){requirePerm(ctx,'view');const d=load(),projects=compute(d),budget=projects.reduce((s,p)=>s+p.duToan,0),spent=projects.reduce((s,p)=>s+p.thucChi,0),slow=projects.flatMap(p=>p.hangMuc.filter(h=>['CHAM','QUA_HAN'].includes(h.trangThaiTienDo.code)).map(h=>({type:'TIEN_DO',congTrinhId:p.id,congTrinhTen:p.ten,hangMucId:h.id,title:h.ten,status:h.trangThaiTienDo}))),cost=projects.filter(p=>['VUOT_DU_TOAN','SAP_VUOT'].includes(p.trangThaiChiPhi.code)).map(p=>({type:'CHI_PHI',congTrinhId:p.id,title:p.ten,status:p.trangThaiChiPhi})),result={kpis:{congTrinhDangThiCong:projects.filter(p=>p.trangThai==='DANG_THI_CONG').length,tienDoTrungBinh:+(projects.reduce((s,p)=>s+p.ptThucTe,0)/Math.max(1,projects.length)).toFixed(2),duToan:budget,thucChi:spent,ptChi:budget?+(spent/budget*100).toFixed(2):null,baoCaoChoDuyet:d.reports.filter(r=>r.trangThai==='CHO_DUYET').length,hangMucCham:slow.length},projects,progressChart:projects.map(p=>({id:p.id,ten:p.ten,keHoach:p.ptKeHoach,thucTe:p.ptThucTe})),costChart:projects.map(p=>({id:p.id,ten:p.ten,duToan:p.duToan,thucChi:p.thucChi})),attention:[...slow,...cost].slice(0,10)};return ctx.role==='KY_THUAT'?stripMoney(result):result},
    api_listProjects(ctx,filter={}){requirePerm(ctx,'view');let rows=compute(load()).filter(p=>(!filter.trangThai||p.trangThai===filter.trangThai)&&(!filter.q||(`${p.ten} ${p.diaDiem}`).toLowerCase().includes(filter.q.toLowerCase())));return ctx.role==='KY_THUAT'?stripMoney(rows):rows},
    api_getProjectDetail(ctx,id){requirePerm(ctx,'view');const d=load(),p=compute(d).find(x=>x.id===id);if(!p)throw Error('Không tìm thấy công trình.');const raw=d.projects.find(x=>x.id===id),curve=[];for(let cursor=raw.ngayKhoiCong;cursor<=raw.ngayHoanThanh;cursor=add(cursor,7)){const point=compute(d,cursor).find(x=>x.id===id);curve.push({ngay:cursor,keHoach:point.ptKeHoach,thucTe:cursor<=today()?point.ptThucTe:null})}const br={VAT_LIEU:{duToan:0,thucChi:0},NHAN_CONG:{duToan:0,thucChi:0},MAY:{duToan:0,thucChi:0},KHAC:{duToan:0,thucChi:0}};d.budgets.filter(b=>b.congTrinhId===id).forEach(b=>{br.VAT_LIEU.duToan+=b.khoiLuong*b.dgVatLieu;br.NHAN_CONG.duToan+=b.khoiLuong*b.dgNhanCong;br.MAY.duToan+=b.khoiLuong*b.dgMay});d.costs.filter(c=>c.congTrinhId===id).forEach(c=>br[c.loai].thucChi+=c.soTien);const result={project:p,workItems:p.hangMuc,progressCurve:curve,recentReports:enrichReports(d,d.reports.filter(r=>r.congTrinhId===id).slice(-20).reverse()),costBreakdown:br,budgetRows:d.budgets.filter(b=>b.congTrinhId===id)};return ctx.role==='KY_THUAT'?stripMoney(result):result},
    api_listReports(ctx,filter={}){requirePerm(ctx,'view');const d=load();return enrichReports(d,d.reports.filter(r=>(!filter.congTrinhId||r.congTrinhId===filter.congTrinhId)&&(!filter.trangThai||r.trangThai===filter.trangThai)&&(!filter.nguoiBaoCao||r.nguoiBaoCao===filter.nguoiBaoCao)).sort((a,b)=>(b.ngay+b.createdAt).localeCompare(a.ngay+a.createdAt)).slice(0,50))},
    api_saveReport(ctx,obj,photos=[]){requirePerm(ctx,'report.create');if(obj.ngay>today())throw Error('Ngày báo cáo không được ở tương lai.');const d=load(),h=d.workItems.find(x=>x.id===obj.hangMucId&&x.congTrinhId===obj.congTrinhId);if(!h)throw Error('Hạng mục không thuộc công trình.');let r=obj.id?d.reports.find(x=>x.id===obj.id):null;if(r&&r.trangThai==='DA_DUYET')throw Error('Báo cáo đã duyệt không thể sửa.');if(r&&r.trangThai!=='TRA_LAI')throw Error('Chỉ báo cáo bị trả lại mới được sửa.');const payload={...(r||{}),...obj,id:r?r.id:nextId(d.reports,'BC-',6),klThucHien:Number(obj.klThucHien),soNhanCong:Number(obj.soNhanCong),photoUrls:[...(r?.photoUrls||[]),...photos.map(p=>'data:'+p.mimeType+';base64,'+p.base64)],anh:'',nguoiBaoCao:ctx.userName,trangThai:'CHO_DUYET',nguoiDuyet:'',ghiChuDuyet:'',ngayDuyet:'',createdAt:r?.createdAt||today()+' 12:00:00'};if(r)Object.assign(r,payload);else d.reports.push(payload);save(d);return payload},
    api_reviewReport(ctx,id,action,note){requirePerm(ctx,'report.review');const d=load(),r=d.reports.find(x=>x.id===id);if(!r||r.trangThai!=='CHO_DUYET')throw Error('Báo cáo không còn chờ duyệt.');if(action==='RETURN'&&!String(note||'').trim())throw Error('Vui lòng nhập lý do trả lại.');Object.assign(r,{trangThai:action==='APPROVE'?'DA_DUYET':'TRA_LAI',nguoiDuyet:ctx.userName,ghiChuDuyet:action==='RETURN'?note:'',ngayDuyet:today()+' 18:00:00'});save(d);return r},
    api_saveCost(ctx,obj){requirePerm(ctx,'cost.create');if(obj.ngay>today())throw Error('Ngày chi phí không được ở tương lai.');if(Number(obj.soTien)<=0)throw Error('Số tiền phải lớn hơn 0.');const d=load(),row={...obj,id:nextId(d.costs,'CP-',6),soTien:Number(obj.soTien),nguoiNhap:ctx.userName,createdAt:today()+' 12:00:00'};d.costs.push(row);save(d);return row},
    api_listCosts(ctx,filter={}){requirePerm(ctx,'money.view');const d=load(),rows=d.costs.filter(c=>(!filter.congTrinhId||c.congTrinhId===filter.congTrinhId)&&(!filter.loai||c.loai===filter.loai)).map(c=>({...c,congTrinhTen:d.projects.find(p=>p.id===c.congTrinhId)?.ten||'',hangMucTen:d.workItems.find(h=>h.id===c.hangMucId)?.ten||''}));return{rows:rows.reverse(),total:rows.reduce((s,c)=>s+c.soTien,0)}},
    api_previewBudgetImport(ctx,projectId,text){requirePerm(ctx,'budget.import');const d=load(),items=d.workItems.filter(h=>h.congTrinhId===projectId),map=Object.fromEntries(items.flatMap(h=>[[h.id,h],[String(h.stt),h]])),parse=(v,decimal)=>{let s=String(v||'').trim().replace(/\s/g,'');if(s.includes('.')&&s.includes(',')){const mark=s.lastIndexOf('.')>s.lastIndexOf(',')?'.':',';s=s.split(mark==='.'?',':'.').join('').replace(mark,'.')}else{const mark=s.includes('.')?'.':s.includes(',')?',':'';if(mark){const p=s.split(mark);s=p.length>2||(!decimal&&p.at(-1).length===3)||(mark==='.'&&p.at(-1).length===3)?p.join(''):p.join('.')}}return Number(s)};let lines=String(text||'').split(/\r?\n/).filter(Boolean);if(lines.length&&!Number.isFinite(parse(lines[0].split('\t')[4],true)))lines.shift();const rows=lines.map((line,i)=>{const c=line.split('\t'),h=map[String(c[0]||'').trim()],q=parse(c[4],true),vl=parse(c[5],false),nc=parse(c[6],false),m=parse(c[7],false),errors=[];if(!h)errors.push('Mã hạng mục không tồn tại.');if(!Number.isFinite(q))errors.push('Khối lượng không hợp lệ.');if(![vl,nc,m].every(Number.isFinite))errors.push('Đơn giá không hợp lệ.');return{line:i+1,valid:!errors.length,errors,congTrinhId:projectId,hangMucId:h?.id||'',hangMucTen:h?.ten||'',maHieu:c[1]||'',noiDung:c[2]||'',donVi:c[3]||'',khoiLuong:Number.isFinite(q)?q:0,dgVatLieu:Number.isFinite(vl)?vl:0,dgNhanCong:Number.isFinite(nc)?nc:0,dgMay:Number.isFinite(m)?m:0,thanhTien:errors.length?0:Math.round(q*(vl+nc+m))}});return{rows,validCount:rows.filter(r=>r.valid).length,errorCount:rows.filter(r=>!r.valid).length,total:rows.reduce((s,r)=>s+r.thanhTien,0)}},
    api_commitBudgetImport(ctx,projectId,rows,mode){requirePerm(ctx,'budget.import');const d=load();if(mode==='REPLACE')d.budgets=d.budgets.filter(b=>b.congTrinhId!==projectId);const added=rows.map(r=>({...r,id:nextId(d.budgets,'DT-',5),congTrinhId:projectId,thanhTien:Math.round(Number(r.khoiLuong)*(Number(r.dgVatLieu)+Number(r.dgNhanCong)+Number(r.dgMay)))}));d.budgets.push(...added);save(d);return added},
    api_saveProject(ctx,obj){requirePerm(ctx,'catalog.manage');const d=load();let row=obj.id?d.projects.find(p=>p.id===obj.id):null;if(row)Object.assign(row,obj);else{row={...obj,id:nextId(d.projects,'CT-',4),createdAt:today()+' 12:00:00'};d.projects.push(row)}save(d);return row},
    api_deleteProject(ctx,id){requirePerm(ctx,'catalog.manage');const d=load();if(d.workItems.some(h=>h.congTrinhId===id))throw Error('Không thể xoá công trình đã có hạng mục.');d.projects=d.projects.filter(p=>p.id!==id);save(d);return true},
    api_saveWorkItem(ctx,obj){requirePerm(ctx,'catalog.manage');const d=load();let row=obj.id?d.workItems.find(h=>h.id===obj.id):null;if(row)Object.assign(row,obj);else{row={...obj,id:nextId(d.workItems,'HM-',4)};d.workItems.push(row)}save(d);return row},
    api_deleteWorkItem(ctx,id){requirePerm(ctx,'catalog.manage');const d=load();if(d.reports.some(r=>r.hangMucId===id)||d.budgets.some(b=>b.hangMucId===id)||d.costs.some(c=>c.hangMucId===id))throw Error('Không thể xoá hạng mục đã có dữ liệu.');d.workItems=d.workItems.filter(h=>h.id!==id);save(d);return true},
    api_resetDemo(ctx){requirePerm(ctx,'demo.reset');seed();return{ok:true}},api_getPhotoUrls(ctx,ids){requirePerm(ctx,'view');return ids.map(id=>({id,url:id}))}
  };
  function runner(success,failure){return new Proxy({}, {get(_,name){if(name==='withSuccessHandler')return fn=>runner(fn,failure);if(name==='withFailureHandler')return fn=>runner(success,fn);return(...args)=>setTimeout(()=>{try{if(!api[name])throw Error('API không tồn tại: '+name);success&&success({ok:true,data:clone(api[name](...args))})}catch(error){if(failure)failure(error);else success&&success({ok:false,error:error.message})}},60)}})}
  window.google={script:{run:runner()}};
})();
